"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_1 = __importDefault(require("./auth"));
const transaction_1 = __importDefault(require("./transaction"));
const blog_1 = __importDefault(require("./blog"));
const analysis_1 = __importDefault(require("./analysis"));
const user_1 = __importDefault(require("./user"));
const test_1 = __importDefault(require("./test"));
const result_1 = __importDefault(require("./result"));
const cloudinary_1 = __importDefault(require("./cloudinary"));
const require_auth_1 = require("../../middlewares/require_auth");
const handle_async_1 = require("../../middlewares/handle_async");
const test_certificate_1 = __importDefault(require("./test_certificate"));
const toeic_testing_1 = __importDefault(require("./toeic_testing"));
const toeic_registration_1 = __importDefault(require("./toeic_registration"));
const toeic_test_session_1 = __importDefault(require("./toeic_test_session"));
const routerA = express_1.default.Router();
routerA.use("/auth", auth_1.default);
routerA.use("/transaction", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), transaction_1.default);
routerA.use("/blog", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), blog_1.default);
routerA.use("/analysis", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), analysis_1.default);
routerA.use("/user", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), user_1.default);
routerA.use("/test", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), test_1.default);
routerA.use("/result", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), result_1.default);
routerA.use("/cloudinary", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), cloudinary_1.default);
routerA.use("/test-certificate", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), test_certificate_1.default);
routerA.use("/toeic-testing", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), toeic_testing_1.default);
routerA.use("/test-registration", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), toeic_registration_1.default);
routerA.use("/toeic-test-session", (0, handle_async_1.handleAsync)(require_auth_1.requireAuth), toeic_test_session_1.default);
exports.default = routerA;
