"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const handle_async_1 = require("../../../middlewares/handle_async");
const transaction_1 = __importDefault(require("../../../controllers/transaction"));
const payment_1 = __importDefault(require("../../../controllers/payment"));
const adminTransactionRouter = express_1.default.Router();
adminTransactionRouter.get("/last-7-months", (0, handle_async_1.handleAsync)(transaction_1.default.getTransactionsLast7Months));
adminTransactionRouter.get("/last-7-days", (0, handle_async_1.handleAsync)(transaction_1.default.getTransactionsLast7Days));
adminTransactionRouter.get("/last-7-years", (0, handle_async_1.handleAsync)(transaction_1.default.getTransactionsLast7Years));
adminTransactionRouter.get("/analyst/new", (0, handle_async_1.handleAsync)(transaction_1.default.getNewTransactionAnalyst));
adminTransactionRouter.get("/", (0, handle_async_1.handleAsync)(transaction_1.default.getTransactions));
adminTransactionRouter.get("/analyst/progress", (0, handle_async_1.handleAsync)(transaction_1.default.getProgressTransaction));
adminTransactionRouter.get("/", (0, handle_async_1.handleAsync)(transaction_1.default.getTransactions));
adminTransactionRouter.get("/status", (0, handle_async_1.handleAsync)(payment_1.default.getStatus));
adminTransactionRouter.post("/update-status", (0, handle_async_1.handleAsync)(transaction_1.default.updateStatus));
exports.default = adminTransactionRouter;
