/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ngQwenf2E92
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function flashcard_manager() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground px-4 md:px-6 py-4 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <BookIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">English Study Manager</span>
        </Link>
        <Button variant="outline">
          <PlusIcon className="mr-2 h-4 w-4" />
          New Flashcard
        </Button>
      </header>
      <main className="flex-1 container mx-auto px-4 md:px-6 py-8">
        <div className="grid gap-6">
          <section>
            <h2 className="text-2xl font-bold mb-4">Flashcard Categories</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              <Card className="p-4 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Vocabulary</h3>
                  <Link
                    href="#"
                    className="text-primary hover:underline"
                    prefetch={false}
                  >
                    View
                  </Link>
                </div>
                <p className="text-muted-foreground">
                  Study common English vocabulary words.
                </p>
                <div className="mt-auto flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">
                    120 flashcards
                  </span>
                  <Button variant="outline" size="sm">
                    Study
                  </Button>
                </div>
              </Card>
              <Card className="p-4 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Grammar</h3>
                  <Link
                    href="#"
                    className="text-primary hover:underline"
                    prefetch={false}
                  >
                    View
                  </Link>
                </div>
                <p className="text-muted-foreground">
                  Improve your understanding of English grammar.
                </p>
                <div className="mt-auto flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">
                    80 flashcards
                  </span>
                  <Button variant="outline" size="sm">
                    Study
                  </Button>
                </div>
              </Card>
              <Card className="p-4 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Idioms</h3>
                  <Link
                    href="#"
                    className="text-primary hover:underline"
                    prefetch={false}
                  >
                    View
                  </Link>
                </div>
                <p className="text-muted-foreground">
                  Learn common English idioms and expressions.
                </p>
                <div className="mt-auto flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">
                    50 flashcards
                  </span>
                  <Button variant="outline" size="sm">
                    Study
                  </Button>
                </div>
              </Card>
              <Card className="p-4 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold">Pronunciation</h3>
                  <Link
                    href="#"
                    className="text-primary hover:underline"
                    prefetch={false}
                  >
                    View
                  </Link>
                </div>
                <p className="text-muted-foreground">
                  Improve your English pronunciation.
                </p>
                <div className="mt-auto flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">
                    60 flashcards
                  </span>
                  <Button variant="outline" size="sm">
                    Study
                  </Button>
                </div>
              </Card>
            </div>
          </section>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground px-4 md:px-6 py-4 flex items-center justify-between">
        <p className="text-sm">
          &copy; 2024 English Study Manager. All rights reserved.
        </p>
        <div className="flex items-center gap-4">
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function CircleAlertIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  );
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
