/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Dv58JebrdS6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";

export function overview2() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <BookIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">TOEIC Prep</span>
        </Link>

        <div className="flex items-center gap-2">
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="md:hidden">
                <MenuIcon className="h-5 w-5" />
                <span className="sr-only">Open menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="right">
              <nav className="grid gap-6 text-lg font-medium">
                <Link
                  href="#"
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  prefetch={false}
                >
                  About
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  prefetch={false}
                >
                  Resources
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  prefetch={false}
                >
                  Practice Tests
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  prefetch={false}
                >
                  Contact
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                  prefetch={false}
                >
                  TOEIC Full Exam
                </Link>
              </nav>
            </SheetContent>
          </Sheet>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar className="h-8 w-8 border-2 border-primary">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>
                <Link
                  href="#"
                  className="flex items-center gap-2"
                  prefetch={false}
                >
                  <div className="h-4 w-4" />
                  <span>Profile</span>
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link
                  href="#"
                  className="flex items-center gap-2"
                  prefetch={false}
                >
                  <div className="h-4 w-4" />
                  <span>Settings</span>
                </Link>
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <Link
                  href="#"
                  className="flex items-center gap-2"
                  prefetch={false}
                >
                  <div className="h-4 w-4" />
                  <span>Logout</span>
                </Link>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1">
        <section
          id="toeic-full-exam"
          className="bg-muted py-12 md:py-16 lg:py-20"
        >
          <div className="container px-4 md:px-6">
            <div className="space-y-6 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">
                TOEIC Full Exam Practice
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Test your TOEIC skills with our full-length practice exam,
                covering all sections of the test.
              </p>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Listening Section</CardTitle>
                    <CardDescription>
                      Practice the listening comprehension portion of the TOEIC
                      exam.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Listening Practice
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Reading Section</CardTitle>
                    <CardDescription>
                      Practice the reading comprehension portion of the TOEIC
                      exam.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Reading Practice
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Full Exam</CardTitle>
                    <CardDescription>
                      Take a full-length TOEIC practice exam to simulate the
                      real test experience.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Full Exam
                    </Link>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section
          id="practice-toeic-part1"
          className="bg-muted py-12 md:py-16 lg:py-20"
        >
          <div className="container px-4 md:px-6">
            <div className="space-y-6 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">
                TOEIC Part 1 Practice
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Test your listening comprehension skills with our TOEIC Part 1
                practice questions.
              </p>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Photographs</CardTitle>
                    <CardDescription>
                      Practice identifying the correct response based on
                      photographs.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Question-Response</CardTitle>
                    <CardDescription>
                      Practice identifying the correct response to a spoken
                      question.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Statements</CardTitle>
                    <CardDescription>
                      Practice identifying the correct statement based on a
                      spoken conversation.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section id="toeic-questions" className="py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6">
            <div className="space-y-6 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">
                TOEIC Practice Questions
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Test your TOEIC skills with our comprehensive collection of
                practice questions, covering all sections of the exam.
              </p>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Listening Questions</CardTitle>
                    <CardDescription>
                      Practice your listening comprehension with our TOEIC-style
                      listening questions.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Listening
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Reading Questions</CardTitle>
                    <CardDescription>
                      Enhance your reading skills with our TOEIC-style reading
                      practice questions.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Reading
                    </Link>
                  </CardContent>
                </Card>
                <Card className="bg-background shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle>Grammar Questions</CardTitle>
                    <CardDescription>
                      Test your English grammar knowledge with our TOEIC-style
                      grammar practice questions.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Grammar
                    </Link>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section
          id="toeic-listening-questions"
          className="bg-muted py-12 md:py-16 lg:py-20"
        >
          <div className="container px-4 md:px-6">
            <div className="max-w-2xl mx-auto space-y-6 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">
                TOEIC Listening Practice
              </h2>
              <p className="text-muted-foreground">
                Test your listening comprehension skills with our TOEIC-style
                listening practice questions.
              </p>
              <div className="grid gap-4">
                <div className="bg-background shadow-sm rounded-lg overflow-hidden">
                  <div className="p-6">
                    <h3 className="text-xl font-semibold">
                      Part 1: Photographs
                    </h3>
                    <p className="text-muted-foreground">
                      Practice identifying the correct response based on
                      photographs.
                    </p>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </div>
                </div>
                <div className="bg-background shadow-sm rounded-lg overflow-hidden">
                  <div className="p-6">
                    <h3 className="text-xl font-semibold">
                      Part 2: Question-Response
                    </h3>
                    <p className="text-muted-foreground">
                      Practice identifying the correct response to a spoken
                      question.
                    </p>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </div>
                </div>
                <div className="bg-background shadow-sm rounded-lg overflow-hidden">
                  <div className="p-6">
                    <h3 className="text-xl font-semibold">
                      Part 3: Statements
                    </h3>
                    <p className="text-muted-foreground">
                      Practice identifying the correct statement based on a
                      spoken conversation.
                    </p>
                    <Link
                      href="#"
                      className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                      prefetch={false}
                    >
                      Start Practice
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
