"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const test_1 = __importDefault(require("./test"));
const payment_1 = __importDefault(require("./payment"));
const upload_test_1 = __importDefault(require("./upload_test"));
const word_1 = __importDefault(require("./word"));
const blog_1 = __importDefault(require("./blog"));
const transcript_test_1 = __importDefault(require("./transcript_test"));
const transcript_test_item_1 = __importDefault(require("./transcript_test_item"));
const test_registration_1 = __importDefault(require("./test_registration"));
const rate_limit_1 = require("../../middlewares/rate_limit");
const routerP = express_1.default.Router();
routerP.use("/test", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), test_1.default);
routerP.use("/payment", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), payment_1.default);
routerP.use("/upload", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), upload_test_1.default);
routerP.use("/word", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), word_1.default);
routerP.use("/blog", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), blog_1.default);
routerP.use("/transcript-test", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), transcript_test_1.default);
routerP.use("/transcript-test-item", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), transcript_test_item_1.default);
routerP.use("/registration", rate_limit_1.RateLimitInstance.createHighLimitMiddleware(), test_registration_1.default);
exports.default = routerP;
